// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWJoJVtPiWNFpbOs5vgH66DhzUQ11ANsM',
    appId: '1:621957741126:android:069147e93eb179a2f46847',
    messagingSenderId: '621957741126',
    projectId: 'sonic-earth-418705',
    storageBucket: 'sonic-earth-418705.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Q6sq5TamEsUksHDJySMj5R9wWf_LCoU',
    appId: '1:621957741126:ios:962e15848b25c644f46847',
    messagingSenderId: '621957741126',
    projectId: 'sonic-earth-418705',
    storageBucket: 'sonic-earth-418705.appspot.com',
    androidClientId: '621957741126-pg77idk4ccnj82h6pvl0d3c6fghl609f.apps.googleusercontent.com',
    iosClientId: '621957741126-1hc7tdtcptnp0nhj66qntl8f7jlmjlvg.apps.googleusercontent.com',
    iosBundleId: 'com.homieeee',
  );
}
